# fly.toml app configuration file generated for autocensor-app on 2025-02-10T16:58:07+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'autocensor-app'
primary_region = 'syd'

[build]
  builder = 'heroku/buildpacks:20'

[env]
  DEEPGRAM_API_KEY = 'YOUR_DEEPGRAM_API_KEY'
  NODE_ENV = 'production'
  PORT = '3000'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
