app = "autocensor-backend"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "heroku/buildpacks:20"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  MONGO_URI = "your_mongo_uri"
  JWT_SECRET = "your_jwt_secret"
  AWS_ACCESS_KEY_ID = "your_aws_access_key"
  AWS_SECRET_ACCESS_KEY = "your_aws_secret_key"
  AWS_REGION = "your_aws_region"
  S3_BUCKET = "your_s3_bucket"
  STRIPE_SECRET_KEY = "your_stripe_secret_key"
  FRONTEND_URL = "https://autocensor-landingpage.fly.dev"
